<template>
  <main class="v-content" data-booted="true" style="padding: 64px 0px 0px 256px;"><div class="v-content__wrap"><div class="container px-6"><div class="my-10"><h3 class="my-5">
    my network
  </h3> <section class="my-10"><h2 class="my-5">
      Your referral link, share it with your friends
    </h2> <div class="d-inline-block mx-auto mb-10 v-card v-sheet theme--light" style="width: 100%;"><div class="container"><div class="row justify-space-between"><div class="col"><div>Your left refferal link</div> <div class="v-input custom-referrer-input v-input--hide-details v-input--is-label-active v-input--is-dirty v-input--is-disabled theme--light v-text-field v-text-field--full-width v-text-field--single-line v-text-field--is-booted"><div class="v-input__control"><div class="v-input__slot"><div class="v-text-field__slot"><input disabled="disabled" id="input-112" type="text"></div></div></div></div> <div class="mt-4">Your right refferal link</div> <div class="v-input custom-referrer-input v-input--hide-details v-input--is-label-active v-input--is-dirty v-input--is-disabled theme--light v-text-field v-text-field--full-width v-text-field--single-line v-text-field--is-booted"><div class="v-input__control"><div class="v-input__slot"><div class="v-text-field__slot"><input disabled="disabled" id="input-113" type="text"></div></div></div></div></div> <div class="d-flex flex-column text-center pl-0 col col-auto"><div class="row ma-0 align-center justify-center"><div class="px-0 col"><button type="button" class="v-btn v-btn--flat v-btn--icon v-btn--round theme--light v-size--default"><span class="v-btn__content"><i aria-hidden="true" class="v-icon notranslate mdi mdi-content-copy theme--light"></i></span></button></div></div> <div class="row ma-0 align-center justify-center"><div class="px-0 col"><button type="button" class="v-btn v-btn--flat v-btn--icon v-btn--round theme--light v-size--default"><span class="v-btn__content"><i aria-hidden="true" class="v-icon notranslate mdi mdi-content-copy theme--light"></i></span></button></div></div></div></div></div></div></section> <section class="direct-referees-section my-10"><h3 class="my-5">
      Your direct referees:
    </h3> <div><div role="alert" class="v-alert my-5 v-sheet theme--dark info"><div class="v-alert__wrapper"><i aria-hidden="true" class="v-icon notranslate v-alert__icon mdi mdi-information theme--dark"></i><div class="v-alert__content">
        You don't have any direct referrees!
    </div></div></div></div></section> <section class="my-10"><h2 class="my-5">
      Your team:
    </h2> <div><div class="pa-2 pa-sm-6 mb-6 mx-auto v-card v-sheet theme--light"><!----> <!----> <hr role="separator" aria-orientation="horizontal" class="v-divider theme--light"> <div class="row"><div class="col-md-6 col-12"><div tabindex="-1" class="pa-0 v-list-item theme--light"><div class="v-list-item__content"><div class="v-list-item__title mb-2 d-flex align-center justify-space-between"><span class="v-chip theme--light v-size--default error"><span class="v-chip__content">Left Investment:</span></span> 0 $
                    </div> <div class="v-list-item__title mb-2 d-flex align-center justify-space-between"><span class="v-chip theme--light v-size--default error"><span class="v-chip__content">Right Investment:</span></span> 0 $
                    </div> <div class="v-list-item__title mb-2 d-flex align-center justify-space-between"><span class="v-chip theme--light v-size--default error"><span class="v-chip__content">Total Invest:</span></span> 0 $
                    </div></div></div></div> <div class="col-md-6 col-12"><div tabindex="-1" class="pa-0 v-list-item theme--light"><div class="v-list-item__content"><div class="v-list-item__title mb-2 d-flex align-center justify-space-between"><span class="v-chip theme--light v-size--default warning"><span class="v-chip__content">Left Members:</span></span> 0
                    </div> <div class="v-list-item__title mb-2 d-flex align-center justify-space-between"><span class="v-chip theme--light v-size--default warning"><span class="v-chip__content">Right Members:</span></span> 0
                    </div></div></div></div></div></div> <div class="row"><div class="col-md-6 col-12"><p class="custom-notif mb-0">*By hovering your mouse on the tree nodes you can see each node's details.</p> <p class="custom-notif mb-0">**By entering a user Id in the input search you can see its details info.</p></div> <div class="col-md-6 col-12"><label for="searchUserInput" class="search-input-label font-weight-bold">Search for a user:</label> <div class="v-input theme--light v-text-field v-text-field--single-line v-text-field--solo v-text-field--is-booted v-text-field--enclosed v-text-field--placeholder"><div class="v-input__control"><div class="v-input__slot"><div class="v-text-field__slot"><input id="searchUserInput" placeholder="User Name" type="text"></div><div class="v-input__append-inner"><button type="button" class="v-btn v-btn--contained theme--light v-size--default error"><span class="v-btn__content"><i aria-hidden="true" class="v-icon notranslate mdi mdi-magnify theme--light"></i></span></button></div></div><div class="v-text-field__details"><div class="v-messages theme--light"><div class="v-messages__wrapper"></div></div></div></div></div></div></div> <div class="v-card v-sheet theme--light"><!----> <div class="binary-tree-wrapper"><div class="org-tree-container"><div class="org-tree"><div class="org-tree-node"><div class="org-tree-node-label"><div class="org-tree-node-label-inner">qx6w7ZOy</div></div><div class="org-tree-node-children"><div class="org-tree-node"><div class="org-tree-node-label"><div class="org-tree-node-label-inner">6BZ5vIne</div></div><div class="org-tree-node-children"><div class="org-tree-node"><div class="org-tree-node-label"><div class="org-tree-node-label-inner"></div></div><div class="org-tree-node-children"><div class="org-tree-node is-leaf"><div class="org-tree-node-label"><div class="org-tree-node-label-inner"></div></div></div><div class="org-tree-node is-leaf"><div class="org-tree-node-label"><div class="org-tree-node-label-inner"></div></div></div></div></div><div class="org-tree-node"><div class="org-tree-node-label"><div class="org-tree-node-label-inner"></div></div><div class="org-tree-node-children"><div class="org-tree-node is-leaf"><div class="org-tree-node-label"><div class="org-tree-node-label-inner"></div></div></div><div class="org-tree-node is-leaf"><div class="org-tree-node-label"><div class="org-tree-node-label-inner"></div></div></div></div></div></div></div></div></div></div></div> <span class="v-tooltip v-tooltip--bottom"><!----></span></div></div></div></section></div></div></div></main>
</template>

<script>
export default {
  name: 'MyNetwork',

}
</script>

<style>
.v-content{
    margin: -100px 0 0 -250px;

   
}
</style>